# Generated by Django 3.1.3 on 2020-11-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date ended',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='date started',
            field=models.DateTimeField(default=None),
        ),
    ]
