# Generated by Django 3.1.3 on 2020-11-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_auto_20201118_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
